{% set name = "google-crc32c" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/python-crc32c/archive/v{{ version }}.tar.gz
  sha256: 24f4015fadc35ec4e2d138d89d00c28976ef8217c6cf8264b4c55ae0c89b1fe1
build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi                                   # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libcrc32c
    - cffi >=1.0.0
  run:
    - python
    - cffi >=1.0.0

test:
  requires:
    - python
    - pip
  imports:
    - google_crc32c
    - google_crc32c.cffi
  commands:
    - python -m pip check


about:
  home: https://github.com/googleapis/python-crc32c
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper for a hardware-based implementation of the CRC32C hashing algorithm

  description: |
    google-crc32c wraps the libcrc32c
    <https://github.com/google/crc32c> package, which is a hardware-based
    implementation of the CRC32C hashing algorithm.
  doc_url: https://github.com/googleapis/python-crc32c
  dev_url: https://github.com/googleapis/python-crc32c

extra:
  recipe-maintainers:
    - tswast
