{% set name = "google-crc32c" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_crc32c-{{ version }}.tar.gz
  sha256: 2bff2305f98846f3e825dbeec9ee406f89da7962accdb29356e4eadc251bd472

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - setuptools
    - libcrc32c
  run:
    - python

test:
  requires:
    - python
    - pip
  imports:
    - google_crc32c
  commands:
    - pip check


about:
  home: https://github.com/googleapis/python-crc32c
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper for a hardware-based implementation of the CRC32C hashing algorithm

  description: |
    google-crc32c wraps the libcrc32c
    <https://github.com/google/crc32c> package, which is a hardware-based
    implementation of the CRC32C hashing algorithm.
  doc_url: https://github.com/googleapis/python-crc32c
  dev_url: https://github.com/googleapis/python-crc32c

extra:
  recipe-maintainers:
    - tswast
    - xylar
