{% set name = "google-crc32c" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/python-crc32c/archive/v{{ version }}.tar.gz
  sha256: 81bd8a6f0b22c8534bdd32e6d98267ab12d9b4fc175eb3cd32d4ed7c03a5f229
build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libcrc32c
    - cffi >=1.0.0
  run:
    - python
    - cffi >=1.0.0

test:
  requires:
    - python
    - pip
  imports:
    - google_crc32c
    - google_crc32c.cffi
  commands:
    - python -m pip check


about:
  home: https://github.com/googleapis/python-crc32c
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python wrapper for a hardware-based implementation of the CRC32C hashing algorithm

  description: |
    google-crc32c wraps the libcrc32c
    <https://github.com/google/crc32c> package, which is a hardware-based
    implementation of the CRC32C hashing algorithm.
  doc_url: https://github.com/googleapis/python-crc32c
  dev_url: https://github.com/googleapis/python-crc32c

extra:
  recipe-maintainers:
    - tswast
